/*
 * Devocionais diários — as 100 reflexões do curso OBREIRO APROVADO,
 * transmitidas pelo Pr. Márcio no grupo dos obreiros.
 *
 * O devocional do dia NÃO é sorteado nem guardado no navegador: ele é
 * calculado a partir da data. Todo mundo que abre o site no mesmo dia lê a
 * mesma reflexão, quem some por um mês volta sincronizado com o calendário,
 * e ao passar do centésimo o ciclo recomeça no primeiro — sem nenhum estado
 * para manter.
 *
 * Parte das reflexões veio em série ("Parte 3 de 4", "continuação"). No grupo
 * elas chegavam em dias seguidos e o leitor acompanhava a sequência; aqui
 * alguém pode cair na parte 5 sem ter visto as anteriores. Por isso cada uma
 * carrega em `serie` o número da parte que a antecede — é o que permite à
 * interface oferecer o link para rever.
 */

export interface SerieDevocional {
    /** Nome da série, mostrado como contexto ("parte 3 de 7"). */
    titulo: string;
    parte: number;
    total: number;
    /** Número do devocional imediatamente anterior. Ausente na primeira parte. */
    anterior?: number;
  }
  
  export interface Devocional {
    /** 1 a 100, na ordem em que foram transmitidas. */
    numero: number;
    /** Parágrafos do texto. String vazia marca a quebra entre blocos. */
    linhas: string[];
    /** Só existe quando a reflexão faz parte de uma série. */
    serie?: SerieDevocional;
  }
  
  /*
   * Dia em que o ciclo começa a contar: nesta data o site mostra o devocional 1.
   * Mude aqui para realinhar o ciclo (ex.: recomeçar num domingo).
   * Formato: ano, mês (0 = janeiro), dia.
   */
  const INICIO_DO_CICLO = Date.UTC(2026, 8, 7);
  
  const UM_DIA = 86_400_000;
  
  export const DEVOCIONAIS: Devocional[] = [
    {
      numero: 1,
      linhas: [
        "Não é de qualquer maneira (condição) que devemos trabalhar na obra de Deus:",
        "• Deus não merece restos ou bagaços de nós",
        "• Não podemos ser pedra de tropeço para ninguém",
        "• Não podemos ser motivo de vergonha para Deus",
      ],
    },
    {
      numero: 2,
      linhas: [
        "Viva os princípios da submissão, da humildade, do respeito, do perdão e da maturidade, pois isso tem grande valor para o atingimento e/ou manutenção da UNIDADE do corpo de Cristo.",
      ],
    },
    {
      numero: 3,
      linhas: [
        "Não deixe o seu coração ser endurecido pelas palavras de obediência, pela disciplina, que Deus comanda na sua vida.",
      ],
    },
    {
      numero: 4,
      linhas: [
        "Jr.48:10 - “Maldito aquele que fizer a obra do Senhor relaxadamente”",
        "",
        "• Somos chamados a fazer o MELHOR --> “Tudo quanto fizerdes, fazei-o de todo o coração, como para o Senhor e não para homens... A Cristo, o Senhor, é que estais servindo.” (Cl.3:23,24)",
      ],
    },
    {
      numero: 5,
      linhas: [
        "Não deixe que o orgulho distorça a mensagem que Deus, de maneira simples e direta, transmite para você.",
      ],
    },
    {
      numero: 6,
      linhas: [
        "Não deixe para amanhã aquilo que Deus está falando contigo no dia que se chama HOJE, por conta de, pelo menos, 3 motivos:",
        "",
        "1. Isso é sinal de arrependimento e/ou de obediência, portanto, sinal de APROVAÇÃO",
        "",
        "2. Amanhã, a voz interior poderá falar mais alto do que a voz de Deus e, assim, anulará ou retardará o que Deus tem para você",
        "",
        "3. O futuro não te pertence",
      ],
    },
    {
      numero: 7,
      linhas: [
        "Seja IRREPREENSÍVEL",
        "• Se sabe o que tem para fazer, faça",
        "• Se sabe o que não deve fazer, não faça",
        "• Se ainda lhe falta conhecimento da Palavra para conhecer as vontades e os limites de Deus, não aceite a zona de conforto, porque a Palavra é muito clara quando diz: “Sede santos e irrepreensíveis perante o Senhor.” (Ef.1:4)",
      ],
    },
    {
      numero: 8,
      linhas: [
        "Somos chamados a viver coerentemente com a nossa Identidade Espiritual (filho de Deus, testemunha de Cristo e templo do Espírito Santo), como OBREIROS APROVADOS!",
      ],
    },
    {
      numero: 9,
      linhas: [
        "Enchei-vos do Espírito. Queira mais da unção de Deus!",
        "Navegue no seguinte caminho:",
        "",
        "• Glorifique a Deus nos tempos difíceis",
        "• Seja fiel a Deus",
        "• Mantenha o equilíbrio em suas decisões",
        "• Persevere na humildade",
        "• Adore a Deus, viva a santificação e seja um instrumento para a glória de Deus",
      ],
    },
    {
      numero: 10,
      linhas: [
        "Clame pelo avivamento!",
        "",
        "Da mesma forma como podemos orar por sabedoria (Tg.1:5), por dons (I Co.14:1), a oração por avivamento está plenamente de acordo com a Palavra: “... aviva a tua obra, ó Senhor, no decorrer dos anos, e no decurso dos anos faze-a conhecida.\"",
      ],
    },
    {
      numero: 11,
      linhas: [
        "Não negocie com a carne, porque Deus sempre verá:",
        "",
        "• obediência parcial como desobediência",
        "• não atendimento a Sua voz como insubmissão",
        "• Não arrependimento como dureza de coração",
        "• permanência no pecado como solo que está (ou é) infértil",
        "• vida cercada de justificativas como alguém que prioriza a si próprio",
      ],
      serie: { titulo: "Não negocie com a carne", parte: 1, total: 2 },
    },
    {
      numero: 12,
      linhas: [
        "(Continuação)",
        "",
        "Não negocie com a carne, porque Deus sempre verá:",
        "",
        "• incredulidade como negação a Sua Palavra",
        "• murmuração como reprovação ao Seu plano",
        "• tudo aquilo que não procede de fé como pecado",
        "• pecado como transgressão a sua vontade, como uma barreira, que faz separação entre Ele e nós",
      ],
      serie: { titulo: "Não negocie com a carne", parte: 2, total: 2, anterior: 11 },
    },
    {
      numero: 13,
      linhas: [
        "Os limites de Deus precisam ser conhecidos, porque eles precisam ser respeitados, já que a inocência não nos livra do pecado, da reprovação de Deus e das consequências.",
      ],
    },
    {
      numero: 14,
      linhas: [
        "Toda CRISE será sempre uma oportunidade para crescer.",
        "",
        "C - Circunstância Momentânea",
        "R - Refletir acerca da sua vida ()",
        "I - Intenções Divinas",
        "S - Segurança no Senhor",
        "E - Expectativa de Crescimento",
        "",
        "() Espiritual, emocional, familiar, laboral",
      ],
    },
    {
      numero: 15,
      linhas: [
        "Apesar de não ser usual a REPREENSÃO PÚBLICA e, consequentemente, soar estranho, tal atitude tem sustentação bíblica, é LÍCITA, conforme o texto abaixo (Mt.18:15-17).",
        "",
        "Cabe, entretanto, o prévio cumprimento de 2 pré-requisitos, extraídos dos 2 primeiros versículos, ou seja, antes da repreensão pública, 2 posicionamentos devem ser atendidos (em particular e perante testemunhas).",
        "",
        "15 Se teu irmão pecar [contra ti], vai argui-lo entre ti e ele só. Se ele te ouvir, ganhaste a teu irmão.",
        "16 Se, porém, não te ouvir, toma ainda contigo uma ou duas pessoas, para que, pelo depoimento de duas ou três testemunhas, toda palavra se estabeleça.",
        "17 E, se ele não os atender, dize-o à igreja; e, se recusar ouvir também a igreja, considera-o como gentio e publicano.",
        "",
        "Isso pode parecer duro para nossas mentes saturadas de tolerância, mas é Jesus falando. A pureza de Sua igreja é de extrema importância para Ele.",
        "",
        "O objetivo da REPREENSÃO PÚBLICA é pedagógico: proteger a igreja, corrigir o erro e prevenir que outros sigam o mesmo caminho.",
        "Ao mesmo tempo, a REGRA GERAL da Bíblia valoriza a CORREÇÃO PRIVADA como forma de preservar a dignidade e promover a transformação.",
      ],
    },
    {
      numero: 16,
      linhas: [
        "Não negocie com os princípios de Deus, pois eles são muros de proteção e segurança para a sua vida e trazem alegria e paz.",
      ],
    },
    {
      numero: 17,
      linhas: [
        "Um grande vencedor sabe transpor suas limitações, tem uma atitude mental positiva e espera / deseja a aprovação de Deus.",
      ],
    },
    {
      numero: 18,
      linhas: [
        "O que é reprovado por Deus, não é para ser degustado por você, porque isso não trará edificação.",
        "Você não precisa desse tipo de conhecimento ou experiência.",
      ],
    },
    {
      numero: 19,
      linhas: [
        "A carne é fraca, mas nunca seremos dominados por algo que não é lícito, que não convém, que não edifica, se não abrirmos as portas dos olhos, dos ouvidos e do coração para essas coisas.",
      ],
    },
    {
      numero: 20,
      linhas: [
        "Antes importa agradar e obedecer a Deus do que aos homens.",
      ],
    },
    {
      numero: 21,
      linhas: [
        "Não troque a sua benção por um prato de lentilhas, por algo momentâneo.",
        "",
        "Não seja impaciente!",
        "Espere o tempo de Deus!",
        "Há tempo para todo propósito debaixo do céu.",
      ],
    },
    {
      numero: 22,
      linhas: [
        "II Pe.1:5-10 - “por isso mesmo, vós, reunindo toda a vossa diligência, associai com a vossa FÉ a VIRTUDE; com a virtude, o CONHECIMENTO; com o conhecimento, o DOMÍNIO PRÓPRIO; com o domínio próprio, a PERSEVERANÇA; com a perseverança, a PIEDADE; com a piedade, a FRATERNIDADE; com a fraternidade, o AMOR.",
        "Porque estas coisas, existindo em vós e em vós aumentando, fazem com que não sejais nem inativos, nem infrutuosos no pleno conhecimento de nosso Senhor Jesus Cristo.",
        "Pois aquele a quem estas coisas não estão presentes é cego, vendo só o que está perto, esquecido da purificação dos seus pecados de outrora.",
        "Por isso, irmãos, procurai, com diligência cada vez maior, confirmar a vossa vocação e eleição; porquanto, procedendo assim, não tropeçareis em tempo algum.”",
      ],
    },
    {
      numero: 23,
      linhas: [
        "\"Finalmente, irmãos, tudo o que é verdadeiro , tudo o que é respeitável , tudo o que é justo , tudo o que é puro , tudo o que é amável , tudo o que é de boa fama, se alguma virtude há e se algum louvor existe, seja isso o que ocupe o vosso pensamento.\" (Fp.4:8)",
        "",
        "Os pensamentos determinam o que somos (quem somos) e o que somos (quem somos) determina o que fazemos.",
        "",
        "E o que pensamos e fazemos vão determinar se estaremos debaixo da aprovação ou da reprovação de Deus.",
      ],
    },
    {
      numero: 24,
      linhas: [
        "A MOTIVAÇÃO em servir a Deus tem estreita relação com a FÉ, com a PERSEVERANÇA, e com a ALEGRIA (fruto do Espírito Santo).",
      ],
    },
    {
      numero: 25,
      linhas: [
        "CINCO coisas INTOLERÁVEIS nos ministérios",
        "",
        "1. Rebeldia - É promotora da morte, da catástrofe. É raiz da incredulidade e da murmuração. Com isso, as promessas são perdidas, as conquistas são atrasadas e o deserto é instalado.",
        "",
        "2. Pecado no altar - Altar deve ser conservado em santidade e sempre em ordem.",
        "",
        "3. Visão diferente - A Bíblia declara que a divisão impede a prosperidade e gera destruição.",
        "",
        "4. Infidelidade dentro dos ministérios - Mais um caminho para grandes perdas e destruição.",
        "",
        "5. Manipuladores Ministeriais - o \"espírito de Jezabel\" (manipulador) usa pessoas para impedir, travar, dominar ou matar pessoas e ministérios.",
      ],
    },
    {
      numero: 26,
      linhas: [
        "ALGUNS INIMIGOS DA EXCELÊNCIA MINISTERIAL",
        "",
        "1. Falta de conhecimento",
        "2. Pressa",
        "3. Decisões unilaterais",
        "4. Negligência",
        "5. Acomodação",
        "6. Rotina",
        "7. Conformismo, que gera palavras de derrota: \"Sempre foi assim\"; \"Isso não tem jeito\"; \"Nada vai mudar\", \"Não tem mais nada para ser feito\", dentre outras.",
        "8. Improvisação",
        "9. Mediocridade / Espírito de miséria no coração",
        "10. Falta de visão espiritual",
        "11. Falta de humildade (lembrando que a humildade gera PROSPERIDADE)",
      ],
    },
    {
      numero: 27,
      linhas: [
        "Quando reconhecemos as nossas FRAQUEZAS:",
        "",
        "1. Procuramos ajuda",
        "2. Vigiamos e protegemos as áreas vulneráveis",
        "3. Diminuímos a possibilidade da queda",
        "4. Corrigimos as deficiências",
        "5. É liberado o PODER DE DEUS em nossas vidas, porque o poder de Deus se aperfeiçoa nas nossas fraquezas",
      ],
    },
    {
      numero: 28,
      linhas: [
        "Pv.16:1 - “O coração do homem pode fazer planos, mas a resposta certa dos lábios vem do Senhor.” (relevância de ouvir a voz de Deus!)",
      ],
    },
    {
      numero: 29,
      linhas: [
        "Não duvide!",
        "",
        "Tg.1:6,7 - “.....o que duvida é semelhante à onda do mar, impelida e agitada pelo vento. Não suponha esse homem que alcançará do Senhor alguma coisa.”",
        "",
        "A dúvida:",
        "• abala a fé",
        "• diminui a capacidade reativa",
        "• cria afastamento de Deus (“tudo o que não procede de fé é pecado”)",
      ],
    },
    {
      numero: 30,
      linhas: [
        "II Co.10:4-5 - “Porque as armas da nossa milícia não são carnais, e sim poderosas em Deus, para destruir fortalezas, anulando nós sofismas e toda altivez que se levante contra o conhecimento de Deus, e levando cativo todo pensamento à obediência de Cristo.”",
      ],
    },
    {
      numero: 31,
      linhas: [
        "Porque falar em UNIDADE?",
        "",
        "1. Porque Deus se alegra!",
        "2. Porque Deus diz que não haverá restrições para TUDO o que intentarmos fazer",
        "3. Porque o diabo trabalha, incansavelmente, para que a unidade não seja estabelecida ou seja destruída. Isso reforça o poder da unidade!",
        "4. Porque precisamos avançar continuamente nessa direção (quão bom quando a visão não é de estagnação e, sim, de excelência!)",
        "",
        "NÃO ABRA MÃO DA UNIDADE!",
        "VOCÊ TEM RESPONSABILIDADE NESSE PROCESSO!!",
      ],
    },
    {
      numero: 32,
      linhas: [
        "Não é de qualquer jeito, ou do nosso jeito, que devemos caminhar no chamado de Deus.",
        "Apesar de nós sermos os chamados, o chamado é de Deus e não nosso!",
        "",
        "Pv.18:9 - “Quem é negligente na sua obra já é irmão do desperdiçador (destruidor)”",
        "",
        "II Tm.2:15 - \"Procura apresentar-te a Deus aprovado, como obreiro que não tem de que se envergonhar, que maneja bem a Palavra da verdade.\"",
      ],
    },
    {
      numero: 33,
      linhas: [
        "Como resistir nos dias maus e vencer as batalhas espirituais? (Parte 1)",
        "",
        "Faça uso das seguintes peças da armadura de Deus:",
        "",
        "1. Cinturão da Verdade → É preciso que a VERDADE (Jesus, Palavra) esteja nos envolvendo, por completo, porque ela nos liberta de cadeias e grilhões, das artimanhas de satanás, de pensamentos errados, de atitudes reprovadas, das dúvidas, da insegurança, assim como, da incredulidade, ao constatar que NÃO IMPORTAM as circunstâncias que estamos envoltos. O que IMPORTA é quem nós somos (filhos de Deus) e que Deus é o nosso provedor!!",
      ],
      serie: { titulo: "Como resistir nos dias maus e vencer as batalhas espirituais", parte: 1, total: 4 },
    },
    {
      numero: 34,
      linhas: [
        "Como resistir nos dias maus e vencer as batalhas espirituais? (Parte 2)",
        "",
        "Faça uso das seguintes peças da armadura de Deus:",
        "",
        "1. Cinturão da Verdade",
        "2. Couraça da justiça → proteção que vem do Jeová Tsidkenu, Senhor Justiça nossa, para a manutenção de algo vital: relacionamento com Ele, porque, na Sua presença, nós TUDO podemos.",
        "",
        "O diabo quer encontrar uma brecha para romper a comunhão entre irmãos, a aliança que nós temos com Deus, mas a Palavra nos diz (Mt.6:1): “Guardai-vos de exercer a vossa justiça diante dos homens, com o fim de serdes visto por eles; doutra sorte, não tereis galardão junto ao vosso Pai Celeste.”",
        "",
        "• “Seja pronto para ouvir, tardio para falar, tardio para se irar, porque a ira do homem não produz a justiça de Deus”",
        "",
        "Não precisamos exercer nossa justiça.",
        "Deus nos honrará.",
        "E a iniquidade, mentira, fofoca, nenhuma arma forjada prevalecerá contra nós, porque o Senhor é quem julga a nossa causa e destrói todo mal.",
      ],
      serie: { titulo: "Como resistir nos dias maus e vencer as batalhas espirituais", parte: 2, total: 4, anterior: 33 },
    },
    {
      numero: 35,
      linhas: [
        "Como resistir nos dias maus e vencer as batalhas espirituais? (Parte 3)",
        "",
        "Faça uso das seguintes peças da armadura de Deus:",
        "",
        "1. Cinturão da Verdade",
        "2. Couraça da Justiça",
        "3. Escudo da Fé",
        "Precisamos embraçar o escudo da fé, PORQUE A FÉ:",
        ". Nos dá a certeza que podemos esperar em Deus as suas promessas",
        ". Nos torna inabaláveis para continuar olhando para Deus e acreditar, mesmo quando tudo diga não ou as circunstâncias sejam desfavoráveis que:",
        "- Todo esforço, perseverança, oração, jejum não serão em vão",
        "- Deus vai abrir um caminho para nos dar escape, vai nos dar a vitória, vai mover suas águas, porque aquilo que não podemos, Ele pode.",
        "",
        "É PRECISO:",
        ". Andar por fé e não pelo que se vê (II Co.5:7)",
        ". Viver pela fé,",
        "PORQUE esta é a vitória que vence o mundo: a nossa fé (I Jo.5:4)",
        "",
        "Sem fé é impossível agradar a Deus (Hb.11:6) e ver a manifestação do Seu poder em nosso favor.",
      ],
      serie: { titulo: "Como resistir nos dias maus e vencer as batalhas espirituais", parte: 3, total: 4, anterior: 34 },
    },
    {
      numero: 36,
      linhas: [
        "Como resistir nos dias maus e vencer as batalhas espirituais? (Parte 4 - Final)",
        "",
        "Faça uso das seguintes peças da armadura de Deus:",
        "",
        "1. Cinturão da Verdade",
        "2. Couraça da Justiça",
        "3. Escudo da Fé",
        "",
        "4. Sandálias da Paz",
        "Sem a paz de Deus, o nosso coração e a nossa mente não estarão imunes aos ataques de satanás!!!",
        "",
        "5. Capacete da Salvação",
        "Importante para proteger nossa mente/coração e nos fazer lembrar, em TODOS os momentos, pensamentos, decisões, atitudes, da Cruz de Cristo (do sacrifício e do amor dele para conosco)",
        "",
        "6. Espada do Espírito (Palavra de Deus)",
        "• Lembre-se: foi com a Palavra que Jesus derrotou o diabo no deserto!",
      ],
      serie: { titulo: "Como resistir nos dias maus e vencer as batalhas espirituais", parte: 4, total: 4, anterior: 35 },
    },
    {
      numero: 37,
      linhas: [
        "No mundo imediatista que vivemos, está cada vez mais difícil respeitar o tempo e o querer de Deus; controlar a ansiedade; se aperfeiçoar, no intuito de fazer o melhor.",
        "",
        "E a negligência desses preceitos traz a reboque não somente a reprovação de Deus (pecado), como afeta a condução da obra de Deus (degradação da oferta e uma porta que se abre para o inimigo trabalhar).",
        "",
        "Deus nos chama a andar num caminho, radicalmente, oposto: PERSEVERANÇA!",
        "",
        "Hb.10:36 - \"Com efeito, tendes necessidade de perseverança, para que, havendo feito a vontade de Deus, alcanceis a promessa.\"",
        "(as tribulações da vida não são um convite para esmorecermos)",
        "",
        "Rm.5:3,4 - \"Não somente isto, mas também nos gloriamos nas tribulações, sabendo que a tribulação produz perseverança; e a perseverança, experiência; e a experiência, esperança.\"",
      ],
      serie: { titulo: "O tempo e a perseverança", parte: 1, total: 2 },
    },
    {
      numero: 38,
      linhas: [
        "O tempo tem sido um grande adversário da obra de Deus e do processo de santificação, seja no curto prazo, pela questão do imediatismo (falta de perseverança), comentado na parte anterior, seja no médio/longo prazo, pela falta de temor e de visão espiritual.",
        "",
        "A consequência disso? Acomodação, relaxamento, indiferença, conivência com as obras do mal e com o erro, estagnação, desgaste ministerial (mau testemunho), brecha (livre acesso ao diabo)",
        "",
        "Jr.48:10 - \"Maldito aquele que fizer a obra do Senhor relaxadamente\"",
        "",
        "• Somos chamados para fazer o MELHOR --> \"Tudo quanto fizerdes, fazei-o de todo o coração, como para o Senhor e não para homens... A Cristo, o Senhor, é que estais servindo.\" (Cl.3:23,24)",
      ],
      serie: { titulo: "O tempo e a perseverança", parte: 2, total: 2, anterior: 37 },
    },
    {
      numero: 39,
      linhas: [
        "5 fatores importantes para a UNIDADE -> submissão, humildade, respeito, perdão, maturidade (Parte 1)",
        "",
        "Unidade (Gn.11:6) - \"e o Senhor disse: Eis que o povo é um, e todos têm a mesma linguagem. Isto é apenas o começo; agora não haverá restrição para tudo que intentam fazer.\"",
        "",
        "1. A submissão gera aprovação, mas, também, gera bom testemunho e quem tem bom testemunho é um agregador. Portanto, a submissão contribui para a UNIDADE.",
        "",
        "2. Humildade -> Gera prosperidade, inclusive, no relacionamento interpessoal.",
        "Somos respeitados pelos nossos testemunhos. Não precisamos de títulos!",
        "A humildade não pode estar presente apenas no falar, mas, principalmente, na maneira de viver a vida, porque senão ela será uma falsa humildade. Isso guarda certa relação com o que Jesus certa vez disse: \"Hipócritas, honram-me com os lábios, mas seus corações estão longe de mim\" (OU SEJA, seus frutos são a realidade daquilo que está no seu coração!)",
        "",
        "• Pv.15:33 - \"o temor do Senhor é a instrução da sabedoria, e a humildade precede a honra\"",
        "",
        "• A palavra convence e o exemplo (bom testemunho) arrasta.",
        "Consequentemente, a humildade contribui para a UNIDADE.",
      ],
      serie: { titulo: "5 fatores importantes para a unidade", parte: 1, total: 2 },
    },
    {
      numero: 40,
      linhas: [
        "5 fatores importantes para a UNIDADE -> submissão, humildade, respeito, perdão, maturidade (Parte 2 - FINAL)",
        "",
        "Unidade (Gn.11:6) - \"e o Senhor disse: Eis que o povo é um, e todos têm a mesma linguagem. Isto é apenas o começo; agora não haverá restrição para tudo que intentam fazer.",
        "",
        "Na parte anterior abordamos a submissão e a humildade.",
        "Vamos, agora, falar sobre os outros 3 fatores.",
        "",
        "3. Respeito -> faça com o seu semelhante aquilo que você gostaria que fizessem contigo (Mt.7:12 - \"Tudo quanto, pois, quereis que os homens vos façam, assim fazei-o vós também a eles\").",
        "O respeito também contribui para a UNIDADE!",
        "",
        "4. Perdão (não é uma opção) -> traz libertação de uma prisão e, também, quebra os efeitos da divisão.",
        "Portanto, mais um fator que contribui para a UNIDADE.",
        "",
        "5. Maturidade -> o risco de ser \"pedra de tropeço\" é menor; há equilíbrio espiritual e, consequentemente, equilíbrio emocional; a capacidade de reação é maior; o caráter egoísta (egocêntrico) não prevalece, porque o coletivo é também valorizado.",
        "Assim, a maturidade é mais um fator que contribui para a UNIDADE.",
      ],
      serie: { titulo: "5 fatores importantes para a unidade", parte: 2, total: 2, anterior: 39 },
    },
    {
      numero: 41,
      linhas: [
        "INICIATIVA",
        "",
        "A iniciativa é uma qualidade que faz com que o indivíduo tome atitudes preventivas ou corretivas, sem que para isso seja preciso alguma ordem.",
        "",
        "Fazendo um paralelo com a vida espiritual: se você já não é mais inocente no conhecimento da vontade de Deus, da orientação de Deus, então, cumpra o que Deus te chama a viver, a fazer, pois: \"aquele que sabe que deve fazer o bem e não o faz nisso está pecando.\" (Tg.4:17)",
        "",
        "Essa é uma das qualidades que mais se espera de um obreiro, isto é, que ele desenvolva a iniciativa.",
        "A obra de Deus sofre por causa de obreiros SEM iniciativa, diante daquilo que está sob seus domínios ou dentro de suas áreas de responsabilidade.",
        "Entretanto, decisões que extrapolem a rotina do dia a dia devem ser apresentadas à liderança do Ministério.",
        "",
        "ATENÇÃO: A INICIATIVA não pode gerar INSUBMISSÃO ou ABUSO DE AUTORIDADE!",
        "",
        "Veja como deve se considerar aquele que espera uma ordem de alguém para executar alguma tarefa, que sabe que tem que ser feita: \"Porventura, terá de agradecer ao servo porque este fez o que lhe havia ordenado? Assim também vós, depois de haverdes feito quanto vos foi ordenado, dizei: Somos servos inúteis, porque fizemos apenas o que devíamos fazer.\" (Lc.17:9,10)",
      ],
    },
    {
      numero: 42,
      linhas: [
        "BOM TESTEMUNHO",
        "",
        "• Viva de acordo com sua identidade espiritual (filho de Deus; testemunha de Cristo; templo do Espírito Santo); afaste-se do pecado (não estimule a tentação!); pratique boas obras",
        "\"cada um é tentado pela sua própria cobiça, quando esta o atrai e seduz\" (Tg.1:14)",
        "",
        "• Cuidado com a boca (controle a língua!)",
        "- \"No muito falar não falta transgressão, mas o que modera os lábios é prudente\" (Pv.10:19)",
        "- \"a morte e a vida estão no poder da língua; o que bem a utiliza come do seu fruto\" (Pv.18:21)",
        "",
        "• Cuidado com quem anda e onde anda (evite estar na roda dos escarnecedores; luz e trevas não se misturam!)",
        "",
        "• Cuidado com as vestes (roupas apertadas, curtas, decotadas, rasgadas, transparente)",
        "",
        "• Homem / mulher de palavra: \"sim, sim; não, não\"",
        "",
        "• Respeite os limites de Deus",
      ],
    },
    {
      numero: 43,
      linhas: [
        "DISCIPLINA",
        "",
        "A disciplina e a instrução do Senhor sempre nos trazem benefícios.",
        "Por disciplina, podemos definir como \"um conjunto de instruções destinado a manter a boa ordem\". E, para nós, cristãos, estas instruções são os preceitos divinos (Sl.19:8) que nos fazem andar no caminho da justiça e da verdade.",
        "",
        "Pv.4:20-22 - \"Filho meu, atenta para as minhas palavras; aos meus ensinamentos inclina os ouvidos. Não os deixes apartar-se dos teus olhos; guarda-os no mais íntimo do teu coração. Porque são vida para quem os acha e saúde, para o seu corpo\".",
        "",
        "Pv.13:18 - \"Pobreza e afronta sobrevêm ao que rejeita a instrução, mas o que guarda a repreensão será honrado.\"",
        "",
        "Pv.3:11,12 - \"Filho meu, não rejeites a disciplina do Senhor, nem te enfades da sua repreensão. Porque o Senhor repreende a quem ama, assim como o pai, ao filho a quem quer bem.\"",
        "",
        "Hb.12:11 - \"Toda disciplina, com efeito, no momento não parece ser motivo de alegria, mas de tristeza; ao depois, entretanto, produz fruto pacífico aos que têm sido por ela exercitados, fruto de justiça.\"",
      ],
    },
    {
      numero: 44,
      linhas: [
        "EQUILÍBRIO",
        "",
        "O equilíbrio não está em um \"caminho do meio\", entre o bem e o mal, mas, sim, na maximização do bem, ou daquilo que é bom, e na eliminação ou minimização do mal, ou daquilo que é prejudicial, conforme os mandamentos de Deus.",
        "",
        "Somos CORPO, ALMA e ESPÍRITO. Portanto, precisamos viver, respectivamente, os EQUILÍBRIOS:",
        "",
        "1. MATERIAL (físico-financeiro)",
        "",
        "• Cuidado para não confundir viver pela fé com viver debaixo de irresponsabilidades financeiras, porque o que se planta, se colhe",
        "",
        "2. EMOCIONAL: não deixando que as emoções desvirtuem o caminho da sabedoria.",
        "",
        "3. E, sobretudo, ESPIRITUAL, na comunhão com Deus, porque nossa luta não é contra carne ou sangue, mas, sim, contra principados e potestades.",
        "",
        "E, por incrível que pareça, há um combustível chamado AMOR que precisa estar em nossos tanques, porque, se ele não estiver presente, estamos suscetíveis ao desequilíbrio espiritual, já que é ele, o AMOR, que nos move a perseverar na presença de Deus e a continuar servindo ao Senhor, em comunhão com os irmãos e com a Igreja, PORQUE:",
        "",
        "• \"o amor é paciente, é benigno; o amor não arde em ciúmes, não se ufana (vangloria), não se ensoberbece (orgulha), não se conduz inconvenientemente, não procura os seus interesses, não se exaspera (ira facilmente), não se ressente do mal; não se alegra com a injustiça, mas regozija-se com a verdade; tudo sofre, tudo crê, tudo espera, tudo suporta.\" (I Co.13:4-7)",
      ],
    },
    {
      numero: 45,
      linhas: [
        "IRREPREENSÍVEL",
        "",
        "Dentre as qualificações necessárias para o OBREIRO APROVADO, Paulo coloca essa virtude (IRREPREENSIVEL) em primeiro lugar.",
        "",
        "Irrepreensível é aquele que não está suscetível a ser repreendido, que dota de boa reputação, de comportamento exemplar.",
        "",
        "Em CI.1:21-22, Paulo diz: \"Ele nos reconciliou... para apresentar-nos perante Ele santos, inculpáveis e irrepreensíveis\".",
        "",
        "Em Fp.2:12b,15 somos exortados a cooperar com o Salvador, não na salvação propriamente dita, mas no desenvolvimento das virtudes que devem caracterizar a vida dos salvos: \"...desenvolvei a vossa salvação com temor e tremor ..... para que vos torneis irrepreensíveis... inculpáveis no meio de uma geração pervertida e corrupta...\"",
        "",
        "• Se sabe o que tem para fazer, faça",
        "• Se sabe o que não deve fazer, não faça",
        "• Se ainda lhe falta conhecimento da Palavra para conhecer as vontades e os limites de Deus, saia de sua zona de conforto, porque a Palavra é muito clara quando diz: \"Sede santos e irrepreensíveis perante o Senhor.\" (Ef.1:4)",
      ],
    },
    {
      numero: 46,
      linhas: [
        "DOMÍNIO PRÓPRIO",
        "",
        "Vivemos em um mundo que, frequentemente, valoriza o excesso, seja na expressão de emoções ou na busca por prazeres materiais.",
        "",
        "No entanto, o domínio próprio é um antídoto poderoso a essa abordagem impulsiva.",
        "",
        "Sendo parte do fruto do Espírito Santo, o domínio próprio significa dizer \"não\" aos impulsos e desejos nocivos, guiando-nos na direção de uma vida equilibrada e com significado.",
      ],
    },
    {
      numero: 47,
      linhas: [
        "NÃO IRASCÍVEL",
        "",
        "O obreiro não pode perder as estribeiras; não pode ser \"pavio curto\", porque a Palavra diz que o pecado já não tem mais domínio sobre a vida dos filhos de Deus.",
        "",
        "Nem toda ira é pecado. A Bíblia fala da ira de Deus, mas esta tem o sentido de \"justa indignação\" e justo juízo. Jesus manifestou indignação repetidas vezes durante o seu ministério terreno.",
        "",
        "Os cristãos, consequentemente, não somente podem, como devem irar-se, manifestando a sua indignação e reprovação ante o pecado.",
        "",
        "De fato, há uma grande \"necessidade de mais ira\" contra o mundo de hoje. Devemos, diante do mal descarado, ficar indignados, não tolerantes, zangados e não apáticos.",
        "",
        "Deus odeia o pecado e Seu povo deve odiá-lo também. Se o mal desperta a ira de Deus, também deve despertar a nossa.",
        "",
        "Ao mesmo tempo, devemos lembrar-nos de que nós próprios somos pecadores, inclinados à intemperança e à vaidade. Portanto, precisamos vigiar para que a ira não se torne pecaminosa.",
        "",
        "Em Ef.4:26-27, Paulo tem o cuidado de equilibrar sua expressão permissiva, \"irai-vos\", com 3 negativas:",
        "• \"Não pequeis\"",
        "• \"Não se ponha o sol sobre a vossa ira\"",
        "• \"Nem deis lugar ao diabo\"",
      ],
    },
    {
      numero: 48,
      linhas: [
        "FIDELIDADE - PARTE 1",
        "",
        "\"Se vocês permanecerem firmes na minha palavra, verdadeiramente serão meus discípulos.\" (Jo.8:31)",
        "",
        "• Nossa fidelidade a Deus está diretamente relacionada ao amor que temos por Deus!",
        "",
        "• Quem não aguenta renunciar, não consegue ser fiel",
        "",
        "• A fidelidade exige, de cada um, renúncias e provas, e tem um preço. Mas, o Senhor nos mostra que as provas pelas quais passamos abrem nossos olhos para O vermos melhor. (Jó disse: \"eu te conhecia só de ouvir, mas agora os meus olhos te veem.\")",
        "",
        "• A fidelidade nos levará à morte em diferentes níveis, mas nos levará a ressurreições em níveis incomparáveis.",
        "",
        "• Apocalipse diz que a fidelidade tem um prazo: \"Sê fiel até a morte.\" (Ap.2:10)",
      ],
      serie: { titulo: "Fidelidade", parte: 1, total: 2 },
    },
    {
      numero: 49,
      linhas: [
        "FIDELIDADE - PARTE 2",
        "",
        "Quem é FIEL:",
        "",
        "• Não comete adultério espiritual, traindo a confiança do Senhor. Pelo contrário, exercita sua fé. (vive pela fé!)",
        "",
        "• Zela por aquilo que lhe foi confiado, como os servos que receberam 5 e 2 talentos do seu senhor e, ao invés, de enterrarem os talentos, os multiplicaram, PORQUE busca agradá-lo.",
        "Não mede esforços em servir, porque não negligencia a responsabilidade de ser um instrumento para a Glória de Deus",
        "",
        "• Cumpre seus votos e compromissos",
        "",
        "• Não troca a aprovação de Deus por NADA!!!",
        "",
        "• Entende a responsabilidade de ser dizimista e ofertante na casa de Deus",
      ],
      serie: { titulo: "Fidelidade", parte: 2, total: 2, anterior: 48 },
    },
    {
      numero: 50,
      linhas: [
        "PERDÃO - PARTE 1",
        "",
        "Sl.34:14 - \"Aparta-te do mal, e faze o bem; busca a paz, e segue-a.\"",
        "",
        "Mt.5:23,24 - \"Se, pois, ao trazeres ao altar a tua oferta, ali te lembrares de que teu irmão tem alguma coisa contra ti, deixa perante o altar a tua oferta, vai primeiro reconciliar-te com teu irmão; e, então, voltando, faze a tua oferta.\"",
        "",
        "O perdão deve preceder a verdadeira adoração a Deus, sabe por quê? Porque se não amamos o nosso irmão (cônjuge / familiar) a quem vemos, não podemos amar a Deus a quem não vemos.",
      ],
      serie: { titulo: "Perdão", parte: 1, total: 3 },
    },
    {
      numero: 51,
      linhas: [
        "PERDÃO - PARTE 2",
        "",
        "PERDOE, PORQUE:",
        "",
        "• Deus ordenou (isso por si só já seria suficiente!)",
        "",
        "• Se não perdoarmos, não seremos perdoados (haverá separação entre Deus e nós!) e nos manteremos presos nas cadeias da amargura",
        "",
        "• A comunhão com Deus é muito mais importante do que viver com raiva, do que a dor que sentimos, do que a mágoa",
        "",
        "• Deus se alegra. Consequentemente, isso se reverte em mais força!! (\"A alegria do Senhor é a vossa força\")",
        "",
        "• Deus tem te perdoado (somos chamados a replicar suas atitudes!)",
      ],
      serie: { titulo: "Perdão", parte: 2, total: 3, anterior: 50 },
    },
    {
      numero: 52,
      linhas: [
        "PERDÃO - PARTE 3",
        "",
        "Libere perdão, deixe o passado para trás e, assim, você será liberto:",
        "- não somente do ciclo de amargura;",
        "- reprovação de Deus;",
        "- como estará livre para avançar para o futuro nesse relacionamento",
        "",
        "Libere perdão, porque \"se não amo o irmão a quem vejo, não posso amar a Deus a quem não vejo.\"",
      ],
      serie: { titulo: "Perdão", parte: 3, total: 3, anterior: 51 },
    },
    {
      numero: 53,
      linhas: [
        "Características das ovelhas - Parte 1",
        "",
        "1.\tLimpas (Dt.14:4)",
        "",
        "• Não viva na constante prática do pecado (até porque o pecado já não tem mais domínio sobre o filho de Deus)",
        "",
        "• Viva a prática do arrependimento, de se humilhar --> importante terminar o dia na condição aprovada!",
        "",
        "• \"Aquele que sabe que deve fazer o bem e não o faz nisso está pecando.\" (Tg.4:17)",
      ],
      serie: { titulo: "Características das ovelhas", parte: 1, total: 8 },
    },
    {
      numero: 54,
      linhas: [
        "Características das ovelhas - Parte 2",
        "",
        "2. Fácil domesticação (Is.53:7)",
        "São facilmente amansadas. Aceitam a disciplina. E, assim, o Senhor também espera de nós!",
        "",
        "Pv.15:32 - \"O que rejeita a disciplina menospreza a sua alma, porém o que atende a repreensão adquire entendimento.\"",
        "",
        "Consequentemente, é amansado do ímpeto de agressividade, de rebeldia, tornando-se facilmente domesticado.",
      ],
      serie: { titulo: "Características das ovelhas", parte: 2, total: 8, anterior: 53 },
    },
    {
      numero: 55,
      linhas: [
        "Características das ovelhas - Parte 3",
        "",
        "3. Mansas (II Sm.12:3)",
        "",
        "• Mt.5:5 - \"Bem-aventurados os mansos, porque herdarão a terra\"",
        "",
        "• Priorize a paz e a comunhão ao invés da contenda",
        "",
        "• Se submeta ao ensino da palavra, porque ela constrói novos valores",
      ],
      serie: { titulo: "Características das ovelhas", parte: 3, total: 8, anterior: 54 },
    },
    {
      numero: 56,
      linhas: [
        "Características das ovelhas - Parte 4",
        "",
        "4. Impotentes (Nm.27:17 / Mt.9:36 / Zc.13:7) E",
        "5.\tIncapazes de se defender (At.20:29) --> precisam do seu pastor para não serem atacadas e mortas pelo lobo",
        "",
        "• Não seja autossuficiente, mas lembre-se de que a suficiência vem do alto (Jeová-Jireh)",
        "",
        "• É necessário reconhecer a dependência de Deus",
        "",
        "• Entenda que não somos nada sem o Senhor --> Pv.21:31 - \"O cavalo prepara-se para a batalha, mas a vitória vem do Senhor.\"",
      ],
      serie: { titulo: "Características das ovelhas", parte: 4, total: 8, anterior: 55 },
    },
    {
      numero: 57,
      linhas: [
        "Características das ovelhas - Parte 5",
        "",
        "6.\tAndam em grupo (Jo.10:3,4): para NÃO se tornarem um alvo fácil; para se ajudarem mutuamente.",
        "",
        "• Aquilo que satanás não consegue por meio da perseguição, ele busca (e consegue), por meio da divisão. Por isso, bom é que os irmãos vivam em união",
        "",
        "• Não podemos abrir mão da UNIDADE do corpo de Cristo",
        "--> I Co.1:10 - \"que não haja entre vós divisões; antes, sejais inteiramente unidos na mesma disposição mental e no mesmo parecer.\"",
        "",
        "--> Gn.11:6 - \"e o Senhor disse: Eis que o povo é um, e todos têm a mesma linguagem. Isto é apenas o começo; agora não haverá restrição para tudo que intentam fazer.\"",
      ],
      serie: { titulo: "Características das ovelhas", parte: 5, total: 8, anterior: 56 },
    },
    {
      numero: 58,
      linhas: [
        "Características das ovelhas - Parte 6",
        "",
        "7.\tFrágis às doenças (Ez.34:4)",
        "",
        "• Assim somos nós, se não combatermos a enfermidade espiritual, chamada pecado, com arrependimento, submissão, santidade, já que Sl.42:7 diz: \"um abismo puxa outro.\"",
        "",
        "8.\tSeletivas na alimentação",
        "(I Cr.4:39,40 / Sl.23:2)",
        "",
        "• Não comem qualquer coisa --> (aponta para) discernimento espiritual",
      ],
      serie: { titulo: "Características das ovelhas", parte: 6, total: 8, anterior: 57 },
    },
    {
      numero: 59,
      linhas: [
        "Características das ovelhas - Parte 7",
        "",
        "9.\tSeguem o Pastor",
        "",
        "Jo.10:27 - \"As minhas ovelhas ouvem a minha voz; eu as conheço, e elas me seguem.\"",
        "",
        "• Não seguem ou ouvem estranhos",
        "",
        "• Precisam do seu pastor para lhe dar a direção",
        "",
        "• Conhecem APENAS o seu pastor, um único pastor. Assim como o pastor deve conhecer suas ovelhas, elas também devem conhecer o seu pastor, para que haja \"UM rebanho e UM pastor\"",
      ],
      serie: { titulo: "Características das ovelhas", parte: 7, total: 8, anterior: 58 },
    },
    {
      numero: 60,
      linhas: [
        "(Complemento da parte anterior)",
        "",
        "Veja o que a Parábola do Bom Pastor (Jo.10:16) diz: \"Ainda tenho outras ovelhas, não deste aprisco (antecipa a missão aos gentios, depois de Pentecostes, e sua completa incorporação à igreja do Senhor); a mim me convém conduzi-las; elas ouvirão a minha voz; então, haverá UM rebanho e UM pastor.\" (PRINCÍPIO BÍBLICO!)",
        "",
        "• Para isso, a ovelha deve reconhecer como seu único pastor, aquele que está cuidando da sua vida espiritual.",
        "A ovelha come somente do pasto do seu pastor e, não, de outros pastos.",
        "",
        "E, trazendo isso para o mundo espiritual, isso é um posicionamento muito sábio, pois:",
        "",
        "1.\tEvita potenciais conflitos doutrinários, que podem gerar conflitos interiores, espirituais",
        "",
        "2.\tEvita comparações (explícitas ou na mente) que, muitas vezes (ou quase sempre), não agregam nenhum valor positivo e podem contaminar outras ovelhas",
        "",
        "3.\tE, ainda, dependendo da frequência com que se alimenta em pastos alheios, isso pode deixá-lo(a) cansado(a) para ter comunhão com as demais ovelhas (membros da sua igreja - AUSÊNCIA) ou para servir, como obreiro(a), na sua igreja",
        "",
        "A ovelha come somente do pasto do seu pastor e, não, de outros pastos.",
      ],
      serie: { titulo: "Características das ovelhas", parte: 8, total: 8, anterior: 59 },
    },
    {
      numero: 61,
      linhas: [
        "Práticas Devocionais - Leitura da Bíblia - Parte 1",
        "",
        "Importância da Palavra",
        "",
        "Sl.1:1,2 - \"Bem-aventurado o homem que não anda no conselho dos ímpios, não se detém no caminho dos pecadores, nem se assenta na roda dos escarnecedores. Antes, o seu prazer está na lei do Senhor, e na sua lei medita de dia e de noite\", porque a Palavra \"é inspirada por Deus e útil para o ensino, para a repreensão, para a correção e para a instrução na justiça.\" (II Tm.3:16)",
        "",
        "Hb.4:12 - \"A Palavra de Deus é viva, e eficaz, e mais cortante do que qualquer espada de dois gumes, e penetra até ao ponto de dividir alma e espírito, juntas e medulas, e é apta para discernir os pensamentos e propósitos do coração. E não há criatura que não seja manifesta na sua presença (deixe de ser alcançada!!)\"",
      ],
      serie: { titulo: "Práticas devocionais — Leitura da Bíblia", parte: 1, total: 3 },
    },
    {
      numero: 62,
      linhas: [
        "Práticas Devocionais - Leitura da Bíblia - Parte 2",
        "",
        "Importância da Palavra",
        "",
        "Jo.8:31,32 - \"Se vós permanecerdes na minha palavra, sois verdadeiramente meus discípulos; e conhecereis a verdade, e a verdade vos libertará.\"",
        "",
        "Sl.119:50 - \"O que me consola na minha angústia é isto: que a tua palavra me vivifica.\"",
        "",
        "Sl.119:105 - \"Lâmpada para os meus pés é a tua palavra e luz para os meus caminhos.\"",
      ],
      serie: { titulo: "Práticas devocionais — Leitura da Bíblia", parte: 2, total: 3, anterior: 61 },
    },
    {
      numero: 63,
      linhas: [
        "Práticas Devocionais - Leitura da Bíblia - Parte 3",
        "",
        "A despeito da inconteste importância da Palavra de Deus, conforme demonstrada nas referências bíblicas das partes anteriores, às vezes, isso parece pouco ou nada para alguns crentes, que simplesmente desprezam a leitura diária da Palavra ou se limitam a um momento relâmpago de intimidade, porque para eles a Palavra é apenas um item a mais de uma agenda cheia de atividades ou de um coração vazio.",
        "",
        "A Palavra não é prioridade, não é pilar de sustentação!!",
        "",
        "Quantas coisas estão perdendo, porque ainda não conseguem enxergar a Palavra como:",
        "• Tesouro acessível",
        "• Muro de proteção para a manutenção da libertação do domínio do pecado",
        "• Alicerce espiritual",
        "• Caminho para a prosperidade",
        "",
        "É preciso que essa verdade esteja nos envolvendo, por completo, porque a VERDADE nos liberta de cadeias, grilhões, das artimanhas de satanás, de pensamentos errados, de atitudes reprovadas, de dúvidas, da insegurança, da incredulidade, dentre outros benefícios.",
        "",
        "Não ler a palavra de Deus, em qualquer dia, indica que você está NEGANDO Cristo, ao demonstrar que existem outras coisas mais importantes para fazer do que escutar a voz de Deus!",
      ],
      serie: { titulo: "Práticas devocionais — Leitura da Bíblia", parte: 3, total: 3, anterior: 62 },
    },
    {
      numero: 64,
      linhas: [
        "\"SANTIFICAI-VOS, porque amanhã o Senhor fará maravilhas no meio de vós.\" (Js.3:5)",
        "",
        "Amanhã é um grande dia!",
        "Quem tem ouvidos, ouça!!",
        "",
        "Deus conhece nossos corações, pensamentos e palavras!!!",
      ],
    },
    {
      numero: 65,
      linhas: [
        "Posicionamentos dos soldados - Parte 1",
        "",
        "Apesar de sermos membros de uma igreja bonita, precisamos manter latente no coração que estamos em um campo de batalha e, CONSTANTEMENTE, em guerra espiritual.",
        "",
        "Para tal, quero reforçar junto aos irmãos, com base na batalha travada por Gideão, e os seus 300 soldados, contra os midianitas, 4 importantes posicionamentos presentes naqueles homens e que a INVB NÃO PODE ABRIR MÃO, EM MOMENTO ALGUM, NA VIDA DOS OBREIROS:",
        "",
        "I. FÉ",
        "",
        "A Palavra diz que tudo que não procede de fé é pecado.",
        "Portanto, TUDO QUE NÃO PROCEDE DE FÉ precisa ser abandonado, DOENÇAS NA ALMA precisam ser curadas, INSTABILIDADE ESPIRITUAL precisa acabar, porque estamos no campo de batalha, NUMA GUERRA REAL, onde só existem 2 resultados: vitória ou derrota.",
        "",
        "Você precisa se enxergar como filho de Deus, como testemunha de Cristo, como templo do Espírito Santo, como soldado do Senhor dos Exércitos, que está num campo de batalha.",
        "",
        "O soldado com as limitações expostas acima não pode estar no campo de batalha, porque não tem a aprovação de Deus.",
        "",
        "Nenhum dos 300 soldados tinha essas restrições.",
      ],
      serie: { titulo: "Posicionamentos dos soldados", parte: 1, total: 5 },
    },
    {
      numero: 66,
      linhas: [
        "Posicionamentos dos soldados - Parte 2 (complemento da parte anterior)",
        "",
        "Apesar de sermos membros de uma igreja bonita, precisamos manter latente no coração que estamos em um campo de batalha e, CONSTANTEMENTE, em guerra espiritual.",
        "Para tal, quero reforçar junto aos irmãos, com base na batalha travada por Gideão, e os seus 300 soldados, contra os midianitas, 4 importantes posicionamentos presentes naqueles homens e que a INVB NÃO PODE ABRIR MÃO, EM MOMENTO ALGUM:",
        "",
        "I. FÉ",
        "",
        "II. Em Jz.7:21, está escrito que os soldados permaneceram em seus lugares.",
        "",
        "No campo de batalha, isso indica a presença de soldados em prontidão, vigilantes, treinados, qualificados, motivados, que sabem o que tem que fazer.",
        "",
        "No caso de líderes de ministério ou de igreja, aponta a qualificação para posicionar o ministério ou a igreja no correto \"lugar\".",
        "",
        "Portanto, soldado displicente, relaxado, indiferente, desmotivado, incapacitado por alguma razão, não pode estar no campo de batalha.",
        "",
        "Não eram essas as características dos 300!",
      ],
      serie: { titulo: "Posicionamentos dos soldados", parte: 2, total: 5, anterior: 65 },
    },
    {
      numero: 67,
      linhas: [
        "Posicionamentos dos soldados - Parte 3 de 4 (complemento das partes anteriores)",
        "",
        "Apesar de sermos membros de uma igreja bonita, precisamos manter latente no coração que estamos em um campo de batalha e, CONSTANTEMENTE, em guerra espiritual.",
        "Para tal, quero reforçar junto aos irmãos, com base na batalha travada por Gideão, e os seus 300 soldados, contra os midianitas, 4 importantes posicionamentos presentes naqueles homens e que a INVB NÃO PODE ABRIR MÃO, EM MOMENTO ALGUM:",
        "",
        "I. FÉ",
        "II. Em Jz.7:21, está escrito que os soldados permaneceram em seus lugares.",
        "",
        "III. OBEDIÊNCIA (obedeceram às ordens de Gideão, ainda que parecessem sem sentido).",
        "",
        "Isso indica, claramente, que soldados indisciplinados, insubmissos, questionadores, que afrontam, que não respeitam qualquer autoridade dentro da igreja não podem estar no campo de batalha.",
        "",
        "Não eram essas as características dos 300!",
      ],
      serie: { titulo: "Posicionamentos dos soldados", parte: 3, total: 5, anterior: 66 },
    },
    {
      numero: 68,
      linhas: [
        "Posicionamentos dos soldados - Parte 4 de 4 (complemento das partes anteriores)",
        "",
        "Apesar de sermos membros de uma igreja bonita, precisamos manter latente no coração que estamos em um campo de batalha e, CONSTANTEMENTE, em guerra espiritual.",
        "Para tal, quero reforçar junto aos irmãos, com base na batalha travada por Gideão, e os seus 300 soldados, contra os midianitas, 4 importantes posicionamentos presentes naqueles homens e que a INVB NÃO PODE ABRIR MÃO, EM MOMENTO ALGUM:",
        "",
        "I. FÉ",
        "II. Em Jz.7:21, está escrito que os soldados permaneceram em seus lugares.",
        "III. OBEDIÊNCIA",
        "",
        "IV. UNIDADE",
        "",
        "Imagina se não houvesse unidade entre os 300 soldados para enfrentar 135.000!",
        "Não podia haver espaço para críticas, pensamentos divergentes, desobediência, individualismo, algo que tem matado igrejas, ministérios.",
        "",
        "Assim, podemos também afirmar que soldado desagregador, desequilibrado, desbalanceado, que não esteja em unicidade com a liderança do ministério ou da igreja não pode estar no campo de batalha.",
        "",
        "Não eram essas as características dos 300!",
      ],
      serie: { titulo: "Posicionamentos dos soldados", parte: 4, total: 5, anterior: 67 },
    },
    {
      numero: 69,
      linhas: [
        "RESUMÃO DA SEMANA",
        "",
        "Posicionamentos do soldado",
        "",
        "Com base nas partes anteriores, advindas de um texto bíblico, REFORÇO TODOS OS POSICIONAMENTOS QUE NÃO PODEM ESTAR PRESENTES em soldados, num campo de batalha:",
        "",
        "I. Incredulidade, doenças na alma e instabilidade espiritual",
        "",
        "II. Displicência, relaxamento, indiferença, desmotivação, incapacitação por alguma razão",
        "",
        "III. Indisciplina, insubmissão, questionador, que afronta, que não respeita uma liderança instituída",
        "",
        "IV. Desagregador, desequilibrado, desbalanceado, que não esteja em unicidade com a liderança do ministério ou da igreja",
        "",
        "Há tempo para tudo!",
        "Só não pode haver espaço para a brecha!!",
        "",
        "Existem 3 importantes OBJETIVOS (PROPÓSITOS), na nossa caminhada cristã:",
        "",
        "• Aperfeiçoar o que já existe E/OU",
        "• Reparar o que já existe E/OU",
        "• Criar o que não existe (está faltando)",
        "",
        "Quem tem ouvidos, ouça!",
        "",
        "\"Melhor é a repreensão franca do que o amor encoberto\" (Pv.27:5)",
      ],
      serie: { titulo: "Posicionamentos dos soldados", parte: 5, total: 5, anterior: 68 },
    },
    {
      numero: 70,
      linhas: [
        "Práticas Devocionais - Oração - Parte 1",
        "",
        "Ao orarmos, entramos no Santo dos Santos e nos colocamos na presença do próprio Deus, em espírito, por meio da fé, valendo-se do sacrifício de Cristo, e falamos com Deus com toda liberdade.",
        "",
        "A oração é o instrumento pelo qual reconhecemos 2 coisas, ao mesmo tempo:",
        "• Estreiteza (limitação) de nossos recursos",
        "• Largueza (amplitude) dos recursos do amor e do poder de Deus",
        "",
        "É a outra via de comunhão com Deus: na 1a (leitura da Bíblia), Deus fala conosco; e na 2a (prática da oração), nós falamos com Deus.",
      ],
      serie: { titulo: "Práticas devocionais — Oração", parte: 1, total: 6 },
    },
    {
      numero: 71,
      linhas: [
        "Práticas Devocionais - Oração - Parte 2",
        "",
        "Elementos da oração",
        "",
        "1.Adoração - você exalta o caráter de Deus, a imensidão, a perfeição e a beleza da criação e se delicia com o próprio Deus.",
        "",
        "2.Ações de graça - você agradece as manifestações de misericórdia, do amor e do poder de Deus em sua vida, família e onde mais você estiver inserido.",
        "",
        "3.Confissão - você se abre e conta a Deus seus pecados, transgressões e fraquezas, admitindo sempre a própria culpa e recorrendo à misericórdia divina.",
        "",
        "4.Extravasamento - você derrama a sua alma perante Deus e fala de seus sustos e medos abertamente, com o propósito de descansar no Senhor.",
        "",
        "5.Súplica - você apresenta suas necessidades, costumeiras ou esporádicas, e clama pela intervenção amorosa e sábia de Deus.",
        "",
        "6.Intercessão - você ora em favor do sofrimento alheio, problemas alheios e necessidades alheias, massacrando o seu egoísmo e exercitando o altruísmo (capacidade de se doar para o próximo sem esperar nada em troca).",
        "",
        "• AS ORAÇÕES NÃO DEVEM SE RESUMIR ÀS SÚPLICAS!",
      ],
      serie: { titulo: "Práticas devocionais — Oração", parte: 2, total: 6, anterior: 70 },
    },
    {
      numero: 72,
      linhas: [
        "Práticas Devocionais - Oração - Parte 3",
        "",
        "A oração exprime a nossa confiança em Deus.",
        "",
        "Mas, o Senhor quer mais do que confiança nele. Quer, também, que o amemos e com Ele tenhamos comunhão mais profunda. Essa é a 2ª razão porque Deus quer que oremos.",
        "",
        "Jesus deu o exemplo disso em seu ministério (subindo ao monte, acordando de madrugada, se separando dos discípulos para ter comunhão com Deus).",
        "",
        "Portanto, se Cristo precisou estar em constante oração, em seu ministério terreno, imagine cada um de nós se não seguirmos o seu exemplo.",
      ],
      serie: { titulo: "Práticas devocionais — Oração", parte: 3, total: 6, anterior: 71 },
    },
    {
      numero: 73,
      linhas: [
        "Práticas Devocionais - Oração - Parte 4",
        "",
        "Além de tomar TODA a Armadura de Deus, para que possamos resistir nos dias maus e permanecer inabaláveis, Ef.6:18 complementa dizendo: não somente revesti-vos de toda armadura, MAS TAMBÉM tome posição: \"com toda a oração e súplica, orando em todo o tempo no Espírito para isto vigiando com toda a perseverança.\"",
        "",
        "• Nada tendes porque não pedis (ou pedis mal)",
        "",
        "• A oração do justo pode muito em seus efeitos, porque tocamos o coração de Deus",
        "",
        "• Quando oramos a Deus, não há nada mais poderoso que Ele possa nos dar do que sua própria presença.",
        "E na presença de Deus, TUDO podemos; nenhum mal prevalece; e o que precisamos, recebemos, porque Ele é o Jeová-Jireh.",
      ],
      serie: { titulo: "Práticas devocionais — Oração", parte: 4, total: 6, anterior: 72 },
    },
    {
      numero: 74,
      linhas: [
        "Práticas Devocionais - Oração - Parte 5",
        "",
        "Oração longa pode não significar a aprovação de Deus!",
        "",
        "Mas, se oramos pouco, se somos indolentes (negligentes / desleixados), certamente:",
        "",
        "1.\tNão cremos, realmente, que a oração consegue, de fato, muita coisa",
        "",
        "2.\tNão amamos Deus como Ele gostaria que fosse amado, porque amar é obedecer, e a Palavra mostra o padrão que Deus estabeleceu para nós: não 5 min / 1h / 3 vezes, por dia, mas orar sem cessar, viver se comunicando com Ele",
        "",
        "3.\tAssim como, não demonstramos interesse em ter uma comunhão mais profunda com o Senhor",
      ],
      serie: { titulo: "Práticas devocionais — Oração", parte: 5, total: 6, anterior: 73 },
    },
    {
      numero: 75,
      linhas: [
        "Práticas Devocionais - Oração - Parte 6",
        "",
        "\"Pai nosso, que estás nos céus, santificado seja o teu nome; venha o teu reino; faça-se a tua vontade, assim na terra como no céu; o pão nosso de cada dia dá-nos hoje; e perdoa-nos as nossas dívidas, assim como nós temos perdoado aos nossos devedores; e não nos deixes cair em tentação; mas livra-nos do mal [pois teu é o reino, o poder e a glória para sempre. Amém]!\" (Mt.6:9-13)",
        "",
        "Certamente, você conhece essa oração, ENSINADA POR JESUS!!",
        "",
        "Num ritmo normal de leitura, essa oração pode ser feita em 28 segundos.",
        "",
        "O que isso quer dizer?",
        "Com certeza, não é um convite para você orar apenas 28 segundos, por dia!",
        "",
        "Deus procura, nas nossas orações, um relacionamento DIRETO, SINCERO, COM TEMOR, COM SIMPLICIDADE, SEM \"RODEIOS\", SEM BUSCA POR VANGLÓRIA, SEM PREOCUPAÇÃO COMO OS OUTROS VÃO AVALIAR NOSSAS ORAÇÕES PÚBLICAS.",
        "",
        "Não precisamos fazer uma oração longa para ser aprovada.",
        "Não precisamos decorar orações-padrão.",
        "Não precisamos ler orações para, realmente, falar com Deus.",
        "Não precisamos recorrer ao ChatGPT para fazer uma oração pública.",
        "",
        "PRECISAMOS QUERER TER INTIMIDADE COM DEUS!!",
      ],
      serie: { titulo: "Práticas devocionais — Oração", parte: 6, total: 6, anterior: 74 },
    },
    {
      numero: 76,
      linhas: [
        "Deus não instituiu a obediência parcial.",
        "Foi o homem que criou esse posicionamento para se adequar aos seus interesses, as suas vontades próprias, àquilo que lhe agrada, as suas limitações, a sua zona de conforto.",
        "",
        "A obediência parcial não cobra renúncia, não precisa de esforço, não indica compromisso.",
        "",
        "E, nela, a aparência (vida de aparência) vale mais do que o conteúdo (vida de obediência)!",
        "",
        "Mas, Deus continua dizendo que a obediência parcial é a mesma coisa que desobediência, negligência, afronta, indiferença, rebelião, religiosidade hipócrita e vazia, porque seus valores não mudam, seus princípios são imutáveis.",
        "",
        "Ele é o mesmo de ontem e será o mesmo amanhã",
      ],
    },
    {
      numero: 77,
      linhas: [
        "Vigilância - Parte 1",
        "",
        "Um crente que não esteja vivendo em constante vigilância é um crente vulnerável, que a qualquer momento pode cair.",
        "",
        "• \"Aquele, pois, que pensa estar em pé veja que não caia.\" (I Co.10:12)",
        "",
        "É preciso:",
        "",
        "1.Vigiar a língua",
        "Porque de uma mesma fonte não pode jorrar o que é doce e o que é amargoso!",
        "",
        "• Pv.10:19 - \"No muito falar não falta transgressão, mas o que modera os lábios é prudente\"",
        "",
        "• Pv.18:21 - \"A morte e a vida estão no poder da língua; o que bem a utiliza come do seu fruto\"",
        "",
        "• Pv.21:23 - \"O que guarda a boca e a língua guarda a sua alma das angústias\"",
        "",
        "• Tg.1:19 - \"seja pronto para ouvir, tardio para falar e tardio para se irar.\"",
        "",
        "• Mensagem clara: a boca precisa ser dominada e não nos dominar!",
        "",
        "• E fato é que \"a boca fala do que o coração está cheio\" (Mt.12:34) E \"onde estiver o teu tesouro, aí estará também o teu coração\" (Mt.6:21)",
      ],
      serie: { titulo: "Vigilância", parte: 1, total: 3 },
    },
    {
      numero: 78,
      linhas: [
        "Vigilância - Parte 2",
        "",
        "Um crente que não esteja vivendo em constante vigilância é um crente vulnerável, que a qualquer momento pode cair.",
        "",
        "• \"Aquele, pois, que pensa estar em pé veja que não caia.\" (I Co.10:12)",
        "",
        "É preciso:",
        "",
        "1.Vigiar a língua",
        "2.Vigiar o que os olhos veem",
        "",
        "Há muitas \"vitrines atrativas no mundo\", que roubam a atenção, o tempo, a santidade, mas, quando nossos olhos estão fixos em Deus, tudo em nós produz vida, porque:",
        "",
        "• Cremos nas promessas do Senhor",
        "",
        "• Sabemos quem somos em Cristo:",
        ". \"um jardim regado, cujas águas nunca faltarão\" (Is.58:11);",
        ". \"o sal da terra e a luz do mundo\" (Mt.5:13-16);",
        ". mais do que vencedores; e",
        ". alguém que tudo pode, porque Ele nos fortalece.",
      ],
      serie: { titulo: "Vigilância", parte: 2, total: 3, anterior: 77 },
    },
    {
      numero: 79,
      linhas: [
        "Vigilância - Parte 3",
        "",
        "Um crente que não esteja vivendo em constante vigilância é um crente vulnerável, que a qualquer momento pode cair.",
        "",
        "• \"Aquele, pois, que pensa estar em pé veja que não caia.\" (I Co.10:12)",
        "",
        "É preciso:",
        "",
        "1.Vigiar a língua",
        "2.Vigiar o que os olhos veem",
        "3.É preciso, também, vigiar em outra importante porta da alma: ouvidos",
        "",
        "Assim como os olhos, nossos ouvidos precisam filtrar as informações que chegam (ou que damos oportunidades).",
        "",
        "4.Vigiar os pensamentos",
        "",
        "Ap. Paulo nos dá o gabarito (8 características): \"irmãos, tudo o que é verdadeiro, tudo o que é respeitável, tudo o que é justo, tudo o que é puro, tudo o que é amável, tudo o que é de boa fama, se alguma virtude há e se algum louvor existe, seja isso o que ocupe o vosso pensamento.\" (Fp.4:8)",
      ],
      serie: { titulo: "Vigilância", parte: 3, total: 3, anterior: 78 },
    },
    {
      numero: 80,
      linhas: [
        "O que significa buscar a Deus em 1º lugar?",
        "(alguns posicionamentos!) - Parte 1",
        "",
        "• Priorizar o Senhor. Sua palavra, sua direção precisam ser desejadas mais do que qualquer coisa. Não podem ser trocadas pela ansiedade, pela precipitação, pelo medo, por sentimentos carnais destrutivos, daninhos ou limitadores",
        "",
        "• Reconhecer que Ele é poderoso em sua vida para sempre conduzi-la em vitória, apesar de suas limitações",
      ],
      serie: { titulo: "O que significa buscar a Deus em 1º lugar", parte: 1, total: 2 },
    },
    {
      numero: 81,
      linhas: [
        "O que significa buscar a Deus em 1º lugar?",
        "(alguns posicionamentos!) - Parte 2",
        "",
        "• Ter confiança e, portanto, esperar nele",
        "",
        "• Preferir orar a se entregar, porque a alegria do Senhor em ver nossas reações se reverte em forças para superarmos nossas limitações",
        "",
        "• Se diminuir para que Ele cresça em você -> E, crescendo o Senhor, cresce o seu poder em nós para que maior seja a glória dele na nossa vida, porque para isso fomos criados, escolhidos e comissionados",
      ],
      serie: { titulo: "O que significa buscar a Deus em 1º lugar", parte: 2, total: 2, anterior: 80 },
    },
    {
      numero: 82,
      linhas: [
        "Marcas de um Grande Vencedor - Parte 1",
        "",
        "I. Saber vencer suas limitações",
        "II. Ter uma atitude mental positiva",
        "III. Esperar / desejar a aprovação de Deus",
        "",
        "I. SABER VENCER SUAS LIMITAÇÕES",
        "",
        "Sempre vamos encontrar limitações ao longo de nossas vidas (internas / família / trabalho / carreira espiritual).",
        "Por isso, não podemos dar a elas um poder maior do que realmente são, porque senão acabaremos abrindo mão de sonhos ou restringindo o agir de Deus, que aponta para um caminho de vitórias, plenitude, MELHOR!!!",
      ],
      serie: { titulo: "Marcas de um Grande Vencedor", parte: 1, total: 11 },
    },
    {
      numero: 83,
      linhas: [
        "Marcas de um Grande Vencedor - Parte 2",
        "",
        "I. Saber vencer suas limitações",
        "II. Ter uma atitude mental positiva",
        "III. Esperar / desejar a aprovação de Deus",
        "",
        "I. SABER VENCER SUAS LIMITAÇÕES (continuação)",
        "",
        "Quero lhe dar 4 conselhos:",
        "",
        "1. Encontre CORAGEM em Deus para AVANÇAR",
        "2. CREIA nas PROMESSAS de Deus para a sua vida",
        "3. TOME POSSE da sua verdadeira IDENTIDADE em Deus",
        "4. DEIXE Deus TRANSFORMAR suas IMPOSSIBILIDADES em MILAGRES",
      ],
      serie: { titulo: "Marcas de um Grande Vencedor", parte: 2, total: 11, anterior: 82 },
    },
    {
      numero: 84,
      linhas: [
        "Marcas de um Grande Vencedor - Parte 3",
        "",
        "I. Saber vencer suas limitações",
        "II. Ter uma atitude mental positiva",
        "III. Esperar / desejar a aprovação de Deus",
        "",
        "II. TER UMA ATITUDE MENTAL POSITIVA",
        "",
        "Veja o que diz Fp.4:6-13!",
        "",
        "\"Não andeis ansiosos de coisa alguma; em tudo, porém, sejam conhecidas, diante de Deus, as vossas petições, pela oração e pela súplica, com ações de graças.",
        "E a paz de Deus, que excede todo o entendimento, guardará o vosso coração e a vossa mente em Cristo Jesus.",
        "Finalmente, irmãos, tudo o que é verdadeiro, tudo o que é respeitável, tudo o que é justo, tudo o que é puro, tudo o que é amável, tudo o que é de boa fama, se alguma virtude há e se algum louvor existe, seja isso o que ocupe o vosso pensamento.",
        "(Não pode haver espaço para: MEDO E PENSAMENTOS DE DERROTA / PEQUENEZ)",
        "",
        "(Continuando)",
        "O que também aprendestes, e recebestes, e ouvistes, e vistes em mim, isso praticai; e o Deus da paz será convosco.",
        "Alegrei-me, sobremaneira, no Senhor porque, agora, uma vez mais, renovastes a meu favor o vosso cuidado; o qual também já tínheis antes, mas vos faltava oportunidade.",
        "Digo isto, não por causa da pobreza, porque aprendi a viver contente em toda e qualquer situação.",
        "Tanto sei estar humilhado como também ser honrado; de tudo e em todas as circunstâncias, já tenho experiência, tanto de fartura como de fome; assim de abundância como de escassez;",
        "tudo posso naquele que me fortalece.\"",
      ],
      serie: { titulo: "Marcas de um Grande Vencedor", parte: 3, total: 11, anterior: 83 },
    },
    {
      numero: 85,
      linhas: [
        "Marcas de um Grande Vencedor - Parte 4",
        "",
        "I. Saber vencer suas limitações",
        "II. Ter uma atitude mental positiva",
        "III. Esperar / desejar a aprovação de Deus",
        "",
        "II. TER UMA ATITUDE MENTAL POSITIVA (continuação)",
        "",
        "Não podemos deixar que a:",
        "",
        "- Ansiedade crie raízes no nosso coração, porque ela mina as nossas forças; abate a alegria, as expectativas que as promessas de Deus onstroem em nossas vidas.",
        "",
        "- Dúvida apague a esperança que o Evangelho planta em nós, porque \"quem duvida é semelhante à onda do mar, impelida e agitada pelo vento. Não suponha que esse homem alcançará do Senhor alguma coisa.\" (Tg.1:6,7)",
        "",
        "- \"Visão de gafanhoto\" tome conta dos nossos olhos. Visão de que somos menores do que os desafios, as lutas, os gigantes, PORQUE NÃO SOMOS.",
      ],
      serie: { titulo: "Marcas de um Grande Vencedor", parte: 4, total: 11, anterior: 84 },
    },
    {
      numero: 86,
      linhas: [
        "Marcas de um Grande Vencedor - Parte 5",
        "",
        "I. Saber vencer suas limitações",
        "II. Ter uma atitude mental positiva",
        "III. Esperar / desejar a aprovação de Deus",
        "",
        "II. TER UMA ATITUDE MENTAL POSITIVA (continuação)",
        "",
        "Certa vez, Jó declarou: \"aquilo que temo me sobrevém e o que receio me acontece\", MAS, tome posse daquilo que o Ap. Paulo disse: tudo podemos naquele que nos fortalece!!",
        "",
        "\"Deus não nos tem dado espírito de covardia, MAS de poder, e de amor, e de moderação\" (II Tm.1:7)",
      ],
      serie: { titulo: "Marcas de um Grande Vencedor", parte: 5, total: 11, anterior: 85 },
    },
    {
      numero: 87,
      linhas: [
        "Marcas de um Grande Vencedor - Parte 6",
        "",
        "I. Saber vencer suas limitações",
        "II. Ter uma atitude mental positiva",
        "III. Esperar / desejar a aprovação de Deus",
        "",
        "III. ESPERAR / DESEJAR A APROVAÇÃO DE DEUS",
        "",
        "Muitas vezes, nos preocupamos com o que as pessoas pensam de nós, falam de nós, mas não nos importamos com o PRINCIPAL: o que Deus pensa a nosso respeito, o que Deus vê quando olha para nós.",
        "",
        "• Paulo disse (serve para uma autorreflexão): \"Acaso busco eu agora a aprovação dos homens ou a de Deus? Ou estou tentando agradar a homens? Se eu ainda estivesse procurando agradar a homens, não seria servo de Cristo.\" (Gl.1:10)",
        "",
        "• Tenha temor a Deus!",
        "",
        "• Faça o MELHOR para Deus (não o \"SEU\" melhor!)",
      ],
      serie: { titulo: "Marcas de um Grande Vencedor", parte: 6, total: 11, anterior: 86 },
    },
    {
      numero: 88,
      linhas: [
        "Marcas de um Grande Vencedor - Parte 7",
        "",
        "I. Saber vencer suas limitações",
        "II. Ter uma atitude mental positiva",
        "III. Esperar / desejar a aprovação de Deus",
        "",
        "III. ESPERAR / DESEJAR A APROVAÇÃO DE DEUS (continuação)",
        "",
        "SAIBA DIZER NÃO:",
        "",
        "1. Para si mesmo -> Domínio próprio (Gl.5:23)",
        "2. Para os escarnecedores -> respeitando os limites de Deus",
        "3. Para o diabo -> resistindo-o (Tg.4:7)",
      ],
      serie: { titulo: "Marcas de um Grande Vencedor", parte: 7, total: 11, anterior: 87 },
    },
    {
      numero: 89,
      linhas: [
        "Marcas de um Grande Vencedor - Parte 8",
        "",
        "I. Saber vencer suas limitações",
        "II. Ter uma atitude mental positiva",
        "III. Esperar / desejar a aprovação de Deus",
        "",
        "III. ESPERAR / DESEJAR A APROVAÇÃO DE DEUS (continuação)",
        "",
        "Não negocie com a carne, porque Deus sempre verá:",
        "",
        "• obediência parcial como desobediência",
        "• não atendimento à sua voz como insubmissão",
        "• Não arrependimento como dureza de coração",
        "• permanência no pecado como solo que está (ou é) infértil",
        "• vida cercada de justificativas como alguém que prioriza a si próprio",
      ],
      serie: { titulo: "Marcas de um Grande Vencedor", parte: 8, total: 11, anterior: 88 },
    },
    {
      numero: 90,
      linhas: [
        "Marcas de um Grande Vencedor - Parte 9",
        "",
        "I. Saber vencer suas limitações",
        "II. Ter uma atitude mental positiva",
        "III. Esperar / desejar a aprovação de Deus",
        "",
        "III. ESPERAR / DESEJAR A APROVAÇÃO DE DEUS (continuação)",
        "",
        "Não negocie com a carne, porque Deus sempre verá:",
        "",
        "• incredulidade como negação a Sua Palavra",
        "• murmuração como reprovação ao Seu plano",
        "• tudo aquilo que não procede de fé como pecado",
        "• pecado como transgressão a sua vontade, como uma barreira, que faz separação entre Ele e nós",
      ],
      serie: { titulo: "Marcas de um Grande Vencedor", parte: 9, total: 11, anterior: 89 },
    },
    {
      numero: 91,
      linhas: [
        "Marcas de um Grande Vencedor - Parte 10",
        "",
        "I. Saber vencer suas limitações",
        "II. Ter uma atitude mental positiva",
        "III. Esperar / desejar a aprovação de Deus",
        "",
        "III. ESPERAR / DESEJAR A APROVAÇÃO DE DEUS (continuação)",
        "",
        "Não negocie com a carne, porque Deus não negocia Seus valores.",
        "",
        "Seus princípios são eternos! -> \"Passará o céu e a terra, porém as minhas palavras não passarão.\" (Mt.24:35)",
      ],
      serie: { titulo: "Marcas de um Grande Vencedor", parte: 10, total: 11, anterior: 90 },
    },
    {
      numero: 92,
      linhas: [
        "Marcas de um Grande Vencedor - Parte 11 (FINAL)",
        "",
        "I. Saber vencer suas limitações",
        "II. Ter uma atitude mental positiva",
        "III. Esperar / desejar a aprovação de Deus",
        "",
        "IV. Não se conformar, buscar sempre a excelência (o conformismo é a marca dos medíocres)",
        "",
        "V. Saber ouvir críticas e enfrentá-las sem perder a doçura (é preciso separar críticas construtivas das destrutivas. Veja se a \"FONTE\" tem legalidade, legitimidade. Certifique se o \"CONTEÚDO\" é verdadeiro ou não)",
        "",
        "VI. Saber dar significado a tudo que faz, porque tem um ideal",
        "",
        "\"Graças a Deus, que nos dá a vitória por intermédio de nosso Senhor Jesus Cristo\" (I Co.15:57)",
      ],
      serie: { titulo: "Marcas de um Grande Vencedor", parte: 11, total: 11, anterior: 91 },
    },
    {
      numero: 93,
      linhas: [
        "As primícias ao Senhor são nossas primeiras e melhores ofertas, e não apenas o que sobra.",
        "",
        "Assim, ofereça as primícias da(o) sua(seu):",
        "1. Vida",
        "2. Tempo",
        "3. Renda",
        "",
        "Quanto a esse último item, NÃO SEJA O CRENTE:",
        "• \"Caim\": Aquele que entrega ofertas apenas quando sobra, ou após gastar com seus desejos, sem a prioridade de entregar o primeiro fruto.",
        "",
        "• Ansioso: Aquele que deixa de ofertar por medo de faltar para contas pessoais, focando na escassez em vez da provisão de Deus.",
        "",
        "• \"Simpatizante\": Frequenta a igreja, mas não se compromete com a consagração financeira, tratando as contribuições como \"doação\" opcional e não como adoração.",
        "",
        "• Teologicamente Desinformado: Acredita que, por não estar sob a lei mosaica, a prática de separar o início da renda não se aplica, negligenciando o princípio de honra.",
      ],
    },
    {
      numero: 94,
      linhas: [
        "Unção de Deus - Parte 1",
        "",
        "• Nos santifica, nos purifica do pecado",
        "• É sinal de dedicação a Deus (filiação a Deus)",
        "",
        "\"Quanto a vós outros, a unção que dele recebestes permanece em vós, e não tendes necessidade de que alguém vos ensine; mas, como a sua unção vos ensina a respeito de todas as coisas, e é verdadeira, e não é falsa, permanecei nele, como também ela vos ensinou.\" (I Jo.2:27)",
      ],
      serie: { titulo: "Unção de Deus", parte: 1, total: 3 },
    },
    {
      numero: 95,
      linhas: [
        "Unção de Deus - Parte 2",
        "",
        "1. Todo aquele que aceita Jesus como seu Salvador, que se converte, recebe a unção do Espírito Santo.",
        "",
        "2. A unção de Deus não é reservada apenas a alguns crentes especiais, é para todos (crentes).",
        "",
        "3. Unção e dom são duas coisas diferentes!",
        "",
        "• A unção indica nossa eleição como povo de Deus",
        "",
        "• O dom é uma benção individual, conferindo uma capacidade específica.",
        "",
        "Quando Cristo ascendeu ao céu, concedeu DONS \"com vistas ao aperfeiçoamento dos santos para o desempenho do seu serviço, para a edificação do Corpo de Cristo\" (Ef.4:12)",
      ],
      serie: { titulo: "Unção de Deus", parte: 2, total: 3, anterior: 94 },
    },
    {
      numero: 96,
      linhas: [
        "Unção de Deus - Parte 3",
        "",
        "Deseja mais unção de Deus?",
        "",
        "1. Glorifique a Deus nos tempos difíceis",
        "2. Seja fiel a Deus",
        "3. Mantenha o equilíbrio em suas decisões",
        "4. Persevere na humildade",
        "5. Adore a Deus, viva a santificação e seja um instrumento para a glória de Deus",
        "",
        "PORQUE TUDO ISSO DEMONSTRA ONDE ESTÁ O TEU CORAÇÃO!",
      ],
      serie: { titulo: "Unção de Deus", parte: 3, total: 3, anterior: 95 },
    },
    {
      numero: 97,
      linhas: [
        "Ambiente para o Avivamento (Hc.3:1,2) - Parte 1",
        "",
        "1. Clamor ao Senhor",
        "2. Palavra de Deus",
        "3. Temor ao Senhor",
        "4. Misericórdia do Senhor",
        "1. Clamor ao Senhor",
        "",
        "Da mesma forma como podemos orar por sabedoria (Tg.1:5), dons (I Co.14:1), a oração por avivamento está plenamente de acordo com a Palavra.",
        "\".. aviva a tua obra, ó Senhor, no decorrer dos anos, e no decurso dos anos faze-a conhecida.\"",
        "",
        "2. Palavra de Deus",
        "",
        "Quando deixamos a Palavra nos vivificar, somos confrontados e produzimos frutos dignos de arrependimento.",
        "É produzida obediência.",
        "Isso alegra o coração de Deus.",
        "Isso é a fonte geradora de avivamento.",
      ],
      serie: { titulo: "Ambiente para o avivamento", parte: 1, total: 2 },
    },
    {
      numero: 98,
      linhas: [
        "Ambiente para o Avivamento (Hc.3:1,2) - Parte 2",
        "",
        "1. Clamor ao Senhor",
        "2. Palavra de Deus",
        "3. Temor ao Senhor",
        "4. Misericórdia do Senhor",
        "3. Temor ao Senhor",
        "",
        ". Se a oração é como o catalisador do avivamento; e o ensino da Palavra, o combustível do avivamento; o temor ao Senhor é a porta de entrada para o avivamento.",
        "",
        ". O temor a Deus é a base para andarmos em Seus caminhos, e para servirmos e amarmos a Ele.",
        "",
        ". Temor a Deus não implica apenas \"respeito\" por Ele, mas inclui a compreensão do quanto Deus repugna o pecado, assim como, temer Seu julgamento do pecado, ter medo da reprovação de Deus.",
        "",
        ". Temor não é ter medo, mas submeter-se a Deus, já que Ele diz: \"sem mim, nada podeis fazer.\"",
        "",
        "4. Misericórdia do Senhor",
        "",
        "O avivamento não é decorrente de campanhas, de estratégias humanas, de méritos humanos, MAS, da vontade e misericórdia de Deus, que não está no nosso domínio.",
        "",
        "Entretanto, isso não inibe nossas ações:",
        "• Orar",
        "• Escutar / viver a Palavra",
        "• Temor a Deus",
      ],
      serie: { titulo: "Ambiente para o avivamento", parte: 2, total: 2, anterior: 97 },
    },
    {
      numero: 99,
      linhas: [
        "Uma das marcas de um povo convertido, com maturidade espiritual, é o prazer de estar na Casa de Deus para adorar a Deus.",
        "",
        "A igreja é um lugar irresistível, com oportunidades imperdíveis de crescimento e que proporciona momentos inesquecíveis para os santos de Deus.",
        "",
        "Mas, na contramão dessa visão estão os desigrejados; estão aqueles com comportamentos que denotam desprezo, descaso, indiferença e desrespeito para com o culto a Deus; estão aqueles que substituem o culto por quaisquer outros compromissos (inclusive o NADA); E estão TAMBÉM muitos pais que decidem não levar seus filhos para a casa do Senhor por motivos (desculpas) que, certamente, Deus não aceita.",
        "",
        "NÃO ESTEJA NA CONTRAMÃO DA VONTADE DE DEUS!",
      ],
    },
    {
      numero: 100,
      linhas: [
        "Muitos dizem: \"Deus, quero ser útil para o Teu Reino\", mas nem todos estão dispostos a pagar o preço.",
        "",
        "SER ÚTIL não é medido por reconhecimento, status ou aplausos, mas, sim, por meio de entrega, renúncia e obediência.",
        "Significa servir no escondido, amar sem retorno e obedecer sem explicação. Deus não busca apenas disposição, mas, também, rendição!!!",
      ],
    },
  ];
  
  /**
   * O devocional de uma data. Sem argumento, o de hoje.
   *
   * A conta usa a data local de quem acessa (não o horário UTC do relógio), então
   * a virada acontece à meia-noite de quem está lendo. O resto da divisão é
   * ajustado para nunca ficar negativo, caso alguém abra o site antes da data de
   * início do ciclo.
   */
  export function devocionalDoDia(data: Date = new Date()): Devocional {
    const hoje = Date.UTC(data.getFullYear(), data.getMonth(), data.getDate());
    const dias = Math.floor((hoje - INICIO_DO_CICLO) / UM_DIA);
    const i = ((dias % DEVOCIONAIS.length) + DEVOCIONAIS.length) % DEVOCIONAIS.length;
    return DEVOCIONAIS[i];
  }
  
  /** Busca pelo número (1 a 100). É como a interface abre a parte anterior. */
  export function devocionalPorNumero(numero: number): Devocional | undefined {
    return DEVOCIONAIS.find((d) => d.numero === numero);
  }
  
  /** Quantos devocionais existem no ciclo. */
  export const TOTAL_DEVOCIONAIS = DEVOCIONAIS.length;