name: Atualizar vídeos do YouTube

on:
  schedule:
    - cron: '0 12,22 * * *'  # Roda 12:00 e 22:00 horas todo dia
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  gerar-json:
    runs-on: ubuntu-latest
    environment: data
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # necessário para histórico completo

      - name: Clonar a branch `data`
        run: |
          git checkout data
          git merge -X main

      - name: Instalar Python e dependências
        run: pip install requests

      - name: Rodar script para gerar videos.json
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python ./scripts/save_last_three_youtube_videos.py

      - name: Copiar videos.json para branch `data`
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add videos.json
          git commit -m "Atualiza videos.json" || echo "Sem mudanças"
          git push origin data